#!/bin/bash
apt-get update \
&& apt-get install -y --no-install-recommends \
   software-properties-common \
   curl dos2unix dnsutils \
   libapparmor1 libedit2 lsb-release gdebi-core \
   ;

RSTUDIO_LATEST=$(wget --no-check-certificate -qO- https://s3.amazonaws.com/rstudio-server/current.ver) \
    && [ -z "$RSTUDIO_VERSION" ] && RSTUDIO_VERSION=$RSTUDIO_LATEST || true \
    && echo $RSTUDIO_VERSION \
    && wget -q http://download2.rstudio.org/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && rm rstudio-server-*-amd64.deb \
    ;

apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
    ;

pip install git+https://github.com/jupyterhub/nbserverproxy.git \
&& jupyter serverextension enable --sys-prefix --py nbserverproxy \
;

pip install git+https://github.com/jupyterhub/nbrsessionproxy.git \
&& jupyter serverextension enable --sys-prefix --py nbrsessionproxy \
&& jupyter nbextension install    --sys-prefix --py nbrsessionproxy \
&& jupyter nbextension enable     --sys-prefix --py nbrsessionproxy \
;

PATH="${PATH}:/usr/lib/rstudio-server/bin" \
&& LD_LIBRARY_PATH="/usr/lib/R/lib:/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server:/opt/conda/lib/R/lib" \
;





cd ~ && wget https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz \
&& tar -zxvf hub-linux-amd64-2.2.9.tgz \
&& ./hub-linux-amd64-2.2.9/install \
&& rm -rf hub* \
&& hub version \
;


